### ISSUE TITLE
Name a tag MIAPPE 1.0

### ISSUE THREAD

**Issue by erlefloch** [MIAPPE/MIAPPE#101]
there is a 1.1 but no 1.0 tag
https://github.com/MIAPPE/MIAPPE/tree/ee7bbf77c98fcea58f685d25d1fae68fc99cbe47

**Comment by cpommier** [comment]
Maybe rather Just an history version in the README, with  a link to the right version. Same on the web site.

**Comment by erlefloch** [comment]
https://stackoverflow.com/questions/4404172/how-to-tag-an-older-commit-in-git

**Comment by cpommier** [comment]
git show ee7bbf7
git tag -a v1.0 ee7bbf7 -m "v1.0 post release taging"

**Comment by cpommier** [comment]
Done, no release since this is too complicated and not worth it
