### ISSUE TITLE
Finalize mermaid data model.

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#107]
the .mmd is not final yet.

**Comment by erlefloch** [comment]
classes in specific color: investigation, study, observed variable : orange; biological material: green
datafile: different shape
add original comments on classes
define default color close to original one
try to keep original arrangement of classes (for example in a mermaid playground)

**Comment by erlefloch** [comment]
I finally choose drawio + svg export, as mermaid diagrams are painful to customize and are furthermore not displayed the same in different browsers and different sites (what worked in https://mermaid.live didnt work in github for example, and mmd diagrams that render well in chromium dont always render in firefox).
The drawio is a xml format, and github displays diffs of SVG very well.
