### ISSUE TITLE
RFC2: Rename 'Statistical design' to 'Experimental design'

### ISSUE THREAD

**Issue by hcwi** [MIAPPE/MIAPPE#13]
Hi,
we suggest that the current _statistical design_ (DM-22, DM-23) be renamed to _experimental design_, according to standard naming convention of Fisher and others (see references at Wikipedia https://en.wikipedia.org/wiki/Design_of_experiments#Notes, or ontologies at Agroportal: http://agroportal.lirmm.fr/search?q=experimental%20design

Additionally, the _map of experimental design_ (DM-29) could follow them directly on the MIAPPE list.

**Comment by DanFaria** [comment]
I see no problem with this change. If all are in agreement, we'll revert to experimental design.

**Comment by cpommier** [comment]
Ok
The term statistical design should be added in the description.
