### ISSUE TITLE
RFC2: Correct example for 'Species'

### ISSUE THREAD

**Issue by hcwi** [MIAPPE/MIAPPE#15]
A suggestion to re-discuss _Genus_ and _Species_ fields (DM-43, DM-44). Perhaps an input from biologists/taxonomists would be valueable here.  

According to basic [references](https://en.wikipedia.org/wiki/Species):

> All species are given a two-part name, a "binomial". The first part of a binomial is the genus to which the species belongs. The second part is called the specific name or the specific epithet (in botanical nomenclature, also sometimes in zoological nomenclature). For example, Boa constrictor is one of four species of the genus Boa.

Having this in mind, the examples in DM-44 should be corrected to _Zea mays; Solanum lycosperium x pennellii_.
Alternatively, if we want only the second part of the name, perhaps for clarity and precision we should rename the fields to _Generic name_ and _Specific name_. But is that a likely use case that the specific name is used on its own?

**Comment by PapoutsoglouE** [comment]
As per the example, this field is intended to hold only the specific epithet portion of the name.  
We discussed renaming the fields in the way you suggest, but in our experience it was more confusing than "genus" and "species", which is the more standard usage - even if formally incorrect.


Additionally, both the MCPD and BrAPI use the same terms for genus and species, so it would be less confusing to keep consistent across the board.  
With regard to use cases, it may be convenient for indexing purposes to keep the generic name and specific epithet separate.

**Comment by Anne-Francoise** [comment]
We can keep genus and species as the title of the field but improve the definition like this:
"Species name (formally species epithet) for the organism...."

**Comment by cpommier** [comment]
Good point. This as been thoroughly discussed and considering the genebank knowledge brought by Anne Françoise, the curent situation is an acceptable compromise between biologis and IT needs.

Decision: Ok for the definition update ("Species name (formally species epithet) for the organism....") and leave field name and content/example as is.
