### ISSUE TITLE
FRC2: Specify numeric fields

### ISSUE THREAD

**Issue by hcwi** [MIAPPE/MIAPPE#16]
A technical issue about the content of co-called numeric fields, e.g. DM-47, DM-48. 
The examples include also the units (`10 m`), making the content a string. 
It should be made clear and consistent in the MIAPPE model wheather the units are expected, or it is strictly numeric field. In the latter case the examples should be corrected.

**Comment by PapoutsoglouE** [comment]
The fields recommend that the numbers be provided in meters, but this is not mandatory. So the unit must be specified. Indeed, this makes the content a string.

To amend the inconsistency, I suggest that we change the indicated format for these fields from "numeric" to "number + unit abbreviation".

**Comment by Anne-Francoise** [comment]
I agree with Eliana

**Comment by BjoernUsadel** [comment]
makes sense and provides a sensible solution

**Comment by cpommier** [comment]
Move to "number + unit abbreviation".
