### ISSUE TITLE
RFC2: Consider broader application of DM-47

### ISSUE THREAD

**Issue by hcwi** [MIAPPE/MIAPPE#17]
Apart from DM-47 _Biological material altitude_  other contexts of 'vertical' dimension can be considered, i.e. depth of underground or under water (submerged) material. 
It might be worth considering this in DM-47's definition, or as a separate attribute.

**Comment by DanFaria** [comment]
Altitude encompasses underground and under water cases: if the value you provide is below ground/water level, then it can be derived (from the set of coordinates) that the material was underground or submerged.
I think it is best not to make the definition too complex as these seem corner-cases. Likewise, adding separate attributes to describe this seems a bit beyond the scope of "minimal information", but if you do feel it is critical information, I would postpone it to MIAPPE v2.

**Comment by Anne-Francoise** [comment]
I agree with Daniel's comment. I think that standards records of altitude manage above and underground position. MIAPPE has been thought only for terrestrial experiments, perhaps, we should clarify this somewhere though.
If we want to address marine (rivers?) experiments, we should contact the relevant community and work with them as we did with the forest tree community to check how useful MIAPPE already is and if it can be improved to better fit their needs and this would be for a V2.

**Comment by cpommier** [comment]
I would advocate for simplicity.
Close. @hcwi if you prefer to rediscuss this in V2, feel free to reopen it. Postpone to V2
