### ISSUE TITLE
Clean examples for DM-58 and DM-59

### ISSUE THREAD

**Issue by hcwi** [MIAPPE/MIAPPE#18]
For the _environmental parameters_ and their _values_ in DM-58 and DM-59 clean the column Examples by moving the additional descriptions

> List environmental parameters in attachment to main MIAPPE table. Examples: 
> Value for each of the above parameters. Examples: 

 to the Definition column

**Comment by DanFaria** [comment]
Agreed.

**Comment by cpommier** [comment]
Agreed

**Comment by cpommier** [comment]
I just worked on this within #26 and #28 
I think it's fully adressed, what do you think ?
