### ISSUE TITLE
RFC2: Rename 'vector' to 'list' in ENV

### ISSUE THREAD

**Issue by hcwi** [MIAPPE/MIAPPE#19]
We suggest avoiding the word 'vector' in the description of ENV-4, ENV-5, and other ENV-xx. The word has quite precise meaning in each domain we touch upon (biology, computer science, maths). To avoid confusion and for consistency with descriptions given for DM-xx, let's better stick to a more general  'list of'.

**Comment by cpommier** [comment]
Agreed
