### ISSUE TITLE
RFC2: Rename 'pH' to 'Acidity'

### ISSUE THREAD

**Issue by hcwi** [MIAPPE/MIAPPE#20]
An issue raised already in the previous RFC by someone (unfortunatelly I don't remember by whom and why it wasn't answered to, but it seemed a good point) to rename ENV-32 from _pH_ (a scale) to _Acidity_ (a property expressed by pH)

**Comment by DanFaria** [comment]
Calling the field acidity would be formally incorrect, as pH is a scale that measures both acidity (on one end of the spectrum) AND basicity (on the other). As soils do range from acidic to alkaline, calling the property acidity may be misleading.

**Comment by cpommier** [comment]
Decision: leave as is
