### ISSUE TITLE
RFC2: Subtaxa/Variety missing from biological material

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#21]
During the WheatIS/PhenoEWG Training, users requested a way to trace variety.
The proposition is to add the following field in Biomaterial:
SubTaxa ; Description : "Name of any subtaxa level, including variety, crossing name, etc.... Can be free text, or key value pair list, or MCPD compliant format (Subtaxon can be used to store any additional taxonomic identifier. The following abbreviations are allowed: ‘subsp.’ (for subspecies); ‘convar.’ (for convariety); ‘var.’ (for variety); ‘f.’ (for form); ‘Group’ (for ‘cultivar group’).)"; Example: "B73, var. B73, var:B73"

**Comment by cpommier** [comment]
Taken fro previous revisions of v1.1 and probably lost during the edition process.

> Infraspecific name
> 
> Key (name of the rank): value (value of the rank) pairs. Ranks can be among the following terms: subspecies, cultivar, variety, subvariety, convariety, group, subgroup, hybrid, line, form, subform
> 
> subspecies:vinifera;cultivar:Pinot noir

**Comment by DanFaria** [comment]
Agree that we should restore "infraspecific name"..............

**Comment by Anne-Francoise** [comment]
agreed

**Comment by PawelKrajewski** [comment]
Agreed

**Comment by cpommier** [comment]
Decision: add the following:
> Infraspecific name
> 
> Key (name of the rank): value (value of the rank) pairs. Ranks can be among the following terms: subspecies, cultivar, variety, subvariety, convariety, group, subgroup, hybrid, line, form, subform
> 
> subspecies:vinifera;cultivar:Pinot noir
>
>ranks suggestions: subspecies,cultivar,variety,subvariety,convariety,group,subgroup,hybrid,line,form,subform
