### ISSUE TITLE
RCF2: Identification of repository in DM-72, DM-81

### ISSUE THREAD

**Issue by alexwhan** [MIAPPE/MIAPPE#25]
DM-72 states "Identifier for the observation unit/sample in a persistant repository, comprises the name of the repository and the identifier of the observation unit therein", and gives the example: "Biosamples: SAMEA4202911".

For a repository as well knows as Biosamples this works on a manual level (ie a human can read it and understand it), but it is very difficult to use programatically, and relies on a human parsing the repository name. 

An ideal solution would be URI, but may not be possible in all instances. Perhaps a minimum of a url of the repository with the identifier?

I also note that the two examples given for DM-72 and DM-81 are identical except for a space after the colon for DM-72. It would be better to be consistent.

**Comment by Anne-Francoise** [comment]
We could systematically add a field to give the possibility to give an URI as it is indeed a kee concept for interoperability.
However, I would keep these not-machine-readable fields to ensure that MIAPPE is also used by communities which are not yet organized at that level but would be keen to open human-reusable datasets (first step!).

**Comment by cpommier** [comment]
Decision: 
keep free text, and encourage the use of URI when possible (discourage URLs)

**Comment by cpommier** [comment]
Added in DM-72 & DM-81: "URI are recommended when possible."
