### ISSUE TITLE
RFC2:  I Term ‘Environment parameter’ (Emphasis)

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#26]
the use of ‘parameter’ will cause a difficulty with the modelling community, e.g. the ICASA initiative of AGMIP. In the modelling community, a parameter is a permanent property of an object (e.g. soil or atmosphere) or of a genotype. For instance, the reflection coefficient of a soil, or the relation between soil water potential and soil moisture (‘water release curve’) have parameters that characterize the studied soil, whereas soil temperature or soil water potential are environmental variables that vary with time and space, even in a given field or growth chamber.

**Suggestion** : - keep “parameter” for permanent properties, 
                        - replace by’ environmental variable’ otherwise
                        -or “protocol attibutes” in other cases, see below

Environment parameter | Name of the environment parameter | List environmental parameters in attachment to main MIAPPE table.Examples: Soil depth, parameter of the water release curve |  
-- | -- | -- | --
Environmental Variable | Output of a sensor,with a name (e.g. temperature or light)  and attributes such as  a  protocol (sensors makes, calibration ) and a unit (e.g. m or µmol m-2 s-1).

**Comment by DanFaria** [comment]
If "parameter" is problematic, I would simply change to "variable" or "attribute", but keep a single field, to avoid making MIAPPE more complex.

**Comment by DanFaria** [comment]
Additionally, environment variables that vary with time and space should be recorded as observations, i.e., in the data; not as metadata (though the type of variable recorded and how it was recorded should be described under observed variable).

**Comment by cpommier** [comment]
Agreed, environment variables should be handled as observations on an environmental trait.
No more field here, just Improving the definition of environment parameter.

**Comment by Anne-Francoise** [comment]
If our use of "parameter" is problematic for modelers (and I see why) we could replace it in the fixed case by: attribute, condition, feature?

**Comment by cpommier** [comment]
Updated the definition of Environment, ( "Environmental variables" are in DM-82 )added :
Environment measures that varies over time, like soil water content, can be recorded as time series of observed Variables (see below)

Describe "Environment parameter" (DM-58) as "permanent" in Definition.  In definition of Environment (DM-57) remove "or experimental conditions".
