### ISSUE TITLE
RFC2: II ‘The Observed variable or Assy is how the measurement has been made’. (Emphasis)

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#27]
This definition bumps with the former point. How the measurement was made is an attribute or a metadata ? 
**Suggestion** : ‘An attribute of an environmental variable is  how the measurement has been made’

**Comment by DanFaria** [comment]
As per my reply in the previous point:

- Environmental variables that changed through time should be described as observed variables, and how they were recorded should be described in this section. The value of the variable through time should be recorded as data (observations).

- Environmental variables (or parameters) that were constant throughout the experiment should be described under the environment section and the values of those parameters should be provided therein.

I'm not sure what the conflict between attribute and metadata is. Everything listed within MIAPPE is metadata, and several fields correspond to attributes / properties.

**Comment by Anne-Francoise** [comment]
I agree with Daniel's coment. See if the definition I proposed makes it more clear?

**Comment by PawelKrajewski** [comment]
Not clear to which DM this comment is related. Maybe to some older version.

**Comment by cpommier** [comment]
It is part of the Environment section but it is indeed hard to understand the section it refers to.
Proposed: solution  adjust the definition of DM-82 Observed variable:
Was:
"An observed variable, typically taking the form of a measured characteristic of the observation unit (plant or environmental trait), associated to the method and unit of measurement."
Now:
"An observed variable describe how a measurement has been made. It typically takes the form of a measured characteristic of the observation unit (plant or environmental trait), associated to the method and unit of measurement."
