### ISSUE TITLE
RFC2: III We are not keen on replacing “treatment” by “factor’.  Furthermore, “cultural practices”, “factors” and “events” are largely redundant (Emphasis)

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#28]
## 3.1- Cultural practices are actions applied to the whole experiment; they should be defined by the action, not by the resulting plant water status. 
For instance, irrigation can be defined with a rule or a volume, not by the level of water stress. For a given level of irrigation, water stress will differ between genotypes, e.g. as a function of root systems or leaf area

a  | a  |  a
--  | --  |  --
Cultural practices | General description of the cultural practices of the study. | Irrigation was applied according needs during summer to prevent water stress. <br>**To be replaced by** Irrigation was applied every week by applying 2/3 of the reference evapotranspiration during the considered weekOrIrrigation was applied in such a way that soil water potential never declined below 20 kPa, or that soil water reserve was always maintained at 80% of total available soil water

## 3.2. ‘Factor’ has a dual definition, either “environmental condition” or “action”

Factor | The object of a study is to ascertain the impact of one or more factors on the biological material. Thus, a factor is, by definition a condition that varies between observation units, which may be biotic (pest, disease interaction) or abiotic (treatment and cultural practice) in nature.
-- | --
Factor description | Free text description of the factor. This include all relevant treatments planificaito and protocole considered for all the plant targeted by a given factor. | Daily watering 1L per plant. | Free text

- In the grey line, first line, ‘factor’ stands for “environmental condition”, this should be  “The object of a study is to ascertain the impact of  **a combination of environmental conditions** on the biological material.
- In the second line, factor is an action (watering), it is in fact redundant with “event” and in good part with “cultural practice” if the latter can have different values depending on experimental treatments.

## Suggestion : 
keep “treatment”, or replace by “action”, or replace by “cultural practices” with values of them in each experimental treatment. For example:

 a  |  a
 -- | --
Experimental Treatment/action | The object of a study is to ascertain the impact a combination of environmental conditions, intended to vary with experimental treatments (but not always do so). Treatments vary with observation units, which may be biotic (pesticide application) or abiotic (watering or cultural practice). Resulting environmental conditions may or may not vary with treatments depending on cases, for instance the biotic status pressure varies with pesticide application only in presence of pests. Soil water status may not vary with irrigation in the presence of continuous rains

**Comment by cpommier** [comment]
Remarks by email:
To me "factor" (or better "experimental factor") is a term more general than "treatment". Factor is any categorical independent variable that can be manipulated, that is, experimental units (or their groups) can be assigned a "factor value" (level). A factor classifies units. In particular, different treatments of biological material (fertilizations) can be a factor, selection of different types of material can be a factor (groups of patients), or assignment of units to different blocks can be a factor (last one - this is how this is used in statistical models, in MIAPPE there are other places to describe experimental design, basically by some "factors"). 

If anything should be changed, I would change "factor" to "experimental factor". The above definition of this term can be found in many places.

If we have two groups of patients (plants), say healthy and ill, we cannot call these groups "different treatments". There is an experimental factor with two levels that classifies the patients.

To some extent, this was explained in the JExpBotany 2015 opinion paper.

**Comment by cpommier** [comment]
> Renaming factor per se has no impact on the work with ISA, if we maintain the usage of the concept/field. It is merely a matter of mapping whatever name the field has to ISA factor.
> 
> My concern is that if you rename the concept, people may deviate from the intended usage. For example, if we revert to "treatment", that word has a broader usage in plant sciences---one can consider that any and all experimental conditions enforced on the plants are in effect "treatments", rather than only the condition(s) that differed between plant groups and which are the object of the experiment.
> I guess we can do our best to document the intended usage in the MIAPPE checklist and complement this with a specific check during validation, to make sure that all "treatments" listed have at least two values among the listed observation units.
> 
> That said, my preferred label for the concept would be "experimental factor", which is more explicit than just "factor" and leaves little room for ambiguity in interpretation.
> 
> 
> If we want to change the usage of the concept/field altogether, e.g. by allowing "treatment" to be used in a broader sense, then that does invalidate the work with ISA.

**Comment by cpommier** [comment]
For 3.2, We must make clearer that on one side there is Factors/treatments and on the other side actions/events that implement/applies it.

**Comment by Anne-Francoise** [comment]
This is the difficult sections from the beginning. The current consensus was to capture at the best:

**What we try to control**
1- the cultural practices (DM28): are not the factor/treatment which effect on the plant material is studied. They are applied to the whole study. **I also agree with 3.1 that it correspond to actions**. In the present version of the checklist, there is no effort to make it machine readable or searchable (free text or attached files). Going further for me should be handled seriously with the community of the agronomists and could be one of the purposes of the V2.
2- the environment (DM58 and DM59): the target parameters of culture that are meant to be kept constant throughout the study. We propose a searchable format with a key pair value.

**What we do not control but we want to record because it should be taken into account in the analysis**
3- the events (DM65, 66, 67, 68). It can be associated to Observation units and the timing is recorded. It is captured to be searchable (with the limitation that there is no standard vocabulary)

**What we study**
4- the factor : it is in a searchable format and it is important to structure the data file of results of the measures. It has to have at least two values and it is associated to two different groups of observation units. I also prefer experimental factor than factor but am not a specialist of thesauri.

**Comment by cpommier** [comment]
## Decision
Considering the different remarks and proposition, I propose the following decisions : 
- MIAPPE 1.1 
**Rename "Factor" to "Experimental  Factor"**

- MIAPPE 2
better clarify the difference between Treatment/Action (No Water Irrigation aka rain fed) and Environmental Characterization (Water deficit)

**Comment by cpommier** [comment]
Added a sentence to the description:
Depending on the level of the data, an experimental factor can be either  "what is the factor applied to the plant" (ie Unwatered), or the "environmental characterisation" (ie if no rain on unwatered plant : Drought ;  if rain on unwatered plant: Irrigated)

**Comment by cpommier** [comment]
Follow up in #37
