### ISSUE TITLE
RFC2: DM35 – institutions may have a Grid ID (used by ORCID) – eg   grid.1031.3

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#30]

**Comment by PapoutsoglouE** [comment]
I am not sure if Grid IDs are so mainstream or critical enough as identifiers that we should cater specifically to them.  

That said, indicated format for this field is free text, so a Grid ID could be provided too. But we need in any case the name and location of the institution.

**Comment by Anne-Francoise** [comment]
They are critical to ensure the uniqueness of the plant material identification. I think that the full name of the Institution can help for manual curation and I also agree that there are several possible ID depending on communities. For instance, Genebanks get their international ID via the VIEW database. Finally, I do not know who gets the right to submit to GRID its institution and ours is not registered on GRID yet. It might be the case for others. So we can suggest with an example but it cannot be enforced more than that yet. May be later?

**Comment by cpommier** [comment]
Decision: suggest with an example but it cannot be enforced more than that yet.
