### ISSUE TITLE
Altitude: should be strictly in meters

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#34]
Or free text

**Comment by Anne-Francoise** [comment]
We have this problem in many fields: do we enforce the international metrics or ISO norms or do we simply recommend them and ensure that all the relevant information to interpret the data is there (I think we did this most of the time). Personally I would go for the second, to avoid rejections of large communities of practices.

**Comment by PapoutsoglouE** [comment]
This is also related to [issue 16](https://github.com/MIAPPE/MIAPPE/issues/16).  

In this particular case, if we recommend a number + abbreviation, it might be a good idea to provide some guidelines as to the abbreviations. For example, `m` usually means meters for altitude, but for attributes such as coordinate uncertainty it could be meters or miles. Feet could be indicated with an `f` or `ft`. 

I don't imagine that there are many of these units in common use across communities, so maybe we should consider including a (very short) such list of abbreviations/meanings in the respective definitions?

**Comment by Anne-Francoise** [comment]
I did not anticipate that the abbreviations could be the same for meter and miles. You are right this is an issue

**Comment by BjoernUsadel** [comment]
I would say make it meters;  for a publications our US colleagues use SI units as well anyway, so they would convert anyhow. Don't get me wrong, I have no problems with ft and even have a rough feeling for cubic feet. 
Maybe quickly ask an US colleague what they think and it they are fine with SI it is m; if not m or ft.

**Comment by cpommier** [comment]
Decision : in meter only, keep m as the abreviation.

**Comment by cpommier** [comment]
Applied the same decision as in #16 
Move to "number + unit abbreviation".
And precised meters only

**Comment by cpommier** [comment]
DM-54, DM-55, DM-21, DM-47
