### ISSUE TITLE
DM-22: statistical design description text should be optional

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#35]
There are existing datasets that don't have this information. And it doesn't make sense for very reduced data.

**Comment by cpommier** [comment]
I think this one is blocker

**Comment by frederikcoppens** [comment]
and BrAPI does not currently contain a field for this, so no BrAPI endpoint would be MIAPPE compliant

**Comment by Anne-Francoise** [comment]
Approved

**Comment by DanFaria** [comment]
I cannot debate the implications of leaving this as optional, as my knowledge of actual datasets is virtually null. However, I think it is important to mention two points:

1) The field being mandatory does not constitute an issue for datasets that don't have a statistical design. The field is textual, so "N/A" would be an acceptable value if that is the case. While this is, for most practical purposes, the same as making the field optional, it is slightly better wrt making sure that studies that had a statistical design have it described.

2) The fact that BrAPI doesn't cover a MIAPPE field should not be an argument for effecting changes to the latter. There are a number of mandatory MIAPPE fields not covered by BrAPI (Eliana has listed them exhaustively after mapping the two resources), so it is clear that an extension of BrAPI will be needed for MIAPPE compliance (in fact, we are already starting discussions with the BrAPI community).

**Comment by BjoernUsadel** [comment]
Daniel has a point here 
if we just were to say experimental design (already changed see other issue) if this makes sense and default to N/A or "none" thus it would also not break from not being covered by BrAPI.
However this might might require an additional mapping as N/A, none, - might thus all mean the same so it would be convenient to drop it. 

That said, if we make it optional even in cases where it would make sense, it will probably not be entered.

**Comment by PawelKrajewski** [comment]
There are situations in which the design type is not evident from the description of the design by factors. Keep obligatory.

**Comment by hcwi** [comment]
I agree that making the field optional might be discouraging from putting anything there by anyone.
 
For the dataset cases given by Cyril, it would still be valuable to know that experimental design is 'unknown' or that it contains 'reduced data'.

**Comment by cpommier** [comment]
OK for leaving as is. N/A an option. I propose to add in the description:
"Can be simply 'NA' or 'none' when it doesn't make sense anymore, like for data computed from several studies"

**Comment by cpommier** [comment]
I Added the proposed sentence. It can be removed if it has the same bad effect as leaving this field not mandatory.

**Comment by cpommier** [comment]
@DanFaria @PapoutsoglouE @hcwi let me know your opinion please

**Comment by hcwi** [comment]
It's still a bit welcoming to putting 'none' ;) But indeed some option for the troublesome cases should be described. How about this:
"Short textual description of the experimental design. In specific cases, e.g. legacy datasets or data computed from several studies, the experimental design can be "unknown"/"NA", "aggregated/reduced data", or simply 'none'."

**Comment by cpommier** [comment]
OK, I 'll do this
