### ISSUE TITLE
DM-25 and DM-26 : Should be optional (0-1)

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#36]
Highly recommended but not always possible.

**Comment by Anne-Francoise** [comment]
Approve

**Comment by DanFaria** [comment]
As in the previous issue, I will mention that these are text fields, and that an "N/A" value is a valid option if the variable is not applicable to the study.

Please consider the trade-off between forcing users to use "N/A" in the few cases where it is not applicable versus allowing users to not bother filling the field in the large majority of cases where it is.

**Comment by Anne-Francoise** [comment]
Agreed!

**Comment by cpommier** [comment]
Added NA as an example
