### ISSUE TITLE
Ensure full coverage of Genbank needs

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#44]
To be discussed with Eurisco team

**Comment by erlefloch** [comment]
Should this be discussed within @AGENTproject ?

**Comment by cpommier** [comment]
MIAPPE has been used for three years in the frame of the H2020 project AGENT, which involves several genebanks. So far, MIAPPE cover their needs. This can be closed. Other issues, more precise, will be opened if need be.
