### ISSUE TITLE
2 factor values per investigation, not by study

### ISSUE THREAD

**Issue by PapoutsoglouE** [MIAPPE/MIAPPE#52]
Related to #51 : In some cases, the effects of different experimental factors are tested across different studies in the same investigation. So the current MIAPPE requirement of a minimum of 2 factor values (per factor) **per study** cannot be fulfilled.

Version 2 should change this requirement so that a minumum of 2 factor values should be present not by study but by investigation.

**Comment by cpommier** [comment]
Duplicate
