### ISSUE TITLE
Release 1.1.2 minor version

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#56]
Let's agree on release text, then @cpommier does the release.
Release text :

**Comment by cpommier** [comment]
Release text:

This is a minor update of MIAPPE v1.1 to correct or clarify the following issues:
- Clarified definition for Observed Variable. Add examples for plant part handling in observation variable.
- Sample handling clarification.
- Observation unit type examples cleaning. 
- Template spreadsheet renaming.

**Comment by AgreementMakerLight** [comment]
My suggestion:

Minor update of MIAPPE v1.1 comprising the following changes:

- Clarified definition and enriched examples for Observed Variable to cover its usage to handle observations of plant parts.
- Clarified definition of Sample, detailing the cases in which it is necessary to declare samples as opposed to using Observed Variables on plant parts.
- Revised and streamlined the list of recommended Observation Unit Types.
- Renamed the MIAPPE spreadsheet template to clarify its purpose.

**Comment by PapoutsoglouE** [comment]
Would we add the mapping table (for MIAPPE/ISA-Tab/BrAPI) to the release after this one?

**Comment by cpommier** [comment]
Yes, let's add the table.

**Comment by cpommier** [comment]
Inform MIAPPE Steering prior releasing.

**Comment by cpommier** [comment]
Minor update of MIAPPE v1.1 comprising the following changes:

- Clarified definition and enriched examples for Observed Variable to cover its usage to handle observations of plant parts.

- Clarified definition of Sample, detailing the cases in which it is necessary to declare samples as opposed to using Observed Variables on plant parts.
- Revised and streamlined the list of recommended Observation Unit Types.
- Renamed the MIAPPE spreadsheet template to clarify its purpose.
- Use of NCBITAXON prefix instead of NCBI (#57 )

**Comment by cpommier** [comment]
Done
