### ISSUE TITLE
[DM42] NCBI taxonomy prefix

### ISSUE THREAD

**Issue by PapoutsoglouE** [MIAPPE/MIAPPE#57]
The preferred way for NCBI taxon information to be given is with the `NCBITAXON` prefix (see [Bioportal page](https://bioportal.bioontology.org/ontologies/NCBITAXON), prefix used by ISA) , as opposed to the shorter `NCBI` that is currently recommended in the MIAPPE checklist.

So the organism field, when an NCBI identifier is used, should take a value such as `NCBITAXON:xxxx` rather than `NCBI:xxxx`.

**Comment by cpommier** [comment]
Handled in #60
