### ISSUE TITLE
Genotypes can be given in the material ID fields

### ISSUE THREAD

**Issue by PapoutsoglouE** [MIAPPE/MIAPPE#61]
The descriptions for these fields should explicitly mention this possibility for clarity.

**Comment by erlefloch** [comment]
commit: https://github.com/MIAPPE/MIAPPE/commit/138be3112bb5fee35d0c9560434598653486554d

**Comment by erlefloch** [comment]
merged to branch v1.2

**Comment by pkersey** [comment]
The meaning of the word "genotype" should be defined as it means different things in different contexts.

**Comment by erlefloch** [comment]
Indeed genotype can mean different things but as the context is well specified here ("The Material source is commonly called germplasm, accession, genotype and even variety for commercial varieties.") it should be fine
