### ISSUE TITLE
sample and biomat other IDs

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#64]
How to handle:

EXOME_ID | VABC_ID | Infinium_ID | Species | Subspecies | Seed Bank | AccessionID | OtherIDs | Accession Name | Ancestory | Lattitude | Longitude | Elevation | Collection Date | Remarks | Category | History | Released | Country of Origin | State/region
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ExomeCapture-DAS5-000004 | DAS5-000004 | WSNP92K.015.01415 | Triticum aestivum subsp. aestivum | subsp. aestivum | AVS | 29020/annuello*27 | Aus29020 = CROC_1/AE.SQUARROSA (517) | Aus29020/annuello*27 | Aus29020/annuello | . | . | . | . | BC1F4 selection | BRD | CULTIVATED | . | AUSTRALIA | Victoria
ExomeCapture-DAS5-000007 | DAS5-000007 | WSNP92K.115.10742 | Triticum aestivum subsp. aestivum | subsp. aestivum | AVS | 29020/annuello*39 | Aus29020 = CROC_1/AE.SQUARROSA (517) | Aus29020/annuello*39 | Aus29020/annuello | . | . | . | . | BC1F4 selection | BRD | CULTIVATED | . | AUSTRALIA | Victoria

**Comment by cpommier** [comment]
In https://github.com/EBIBioSamples/biosamples-v4/blob/biohackathon_miappe_checklist/webapps/core/src/main/resources/schemas/certification/plant-miappe.json a 
"synonym" filed that contains several alternate IDs and names following the MIAPPE "key":"value" used in MIAPPE such as in Material Source ID . Inthis one we concatenate Holding institute and accession number : INRAE:32Mtp1342 . Here we would have the following synonyms : EXOM_ID:651ert4 PROJETC_ID:3214

**Comment by cpommier** [comment]
See also (duplicate ?) #67

**Comment by cpommier** [comment]
Another possiblity: encourage the creation of additionnal columns

**Comment by cpommier** [comment]
In fact this seems to be handled already in MIAPPE with sample.externalID:  `EXOME_ID:ExomeCapture-DAS5-000004;Biosample:SAMEA4202911`

**Comment by erlefloch** [comment]
- Phenotyping example : phenotyping data outside EBI archives to be linked with genomic data conserved in EBI archives
(relevant for MIAPPE) -> proposition to add the Biosamples ID(s) as a synonym of the phenotyping observation unit ID. Examples could come from the AGENT project once published.  Or in a published GWAS paper.

- Multi-omic example: linking data in several EBI archives

**Comment by erlefloch** [comment]
proposition: 
create biologicamMaterial.external_ID to be consistent with sample and observation unit.
See previous example.
