### ISSUE TITLE
Add Trait decomposition to Entity and Attribute + Variable description

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#66]
Extension taken from Crop Ontology and Mungall et al. 2009.
It would increase th ease of use for information systems and Observed Variables managment tools.
Consider also adding the optioanll "Level". It is the agregation level: genotypic mean or measure on one plant/group of plant.

**Comment by cpommier** [comment]
EMPHASIS uses Entity / Characteristic

**Comment by cpommier** [comment]
Proposition: Canopy is whatever surface (morceau de terrain)  sur laquelle on fait une mesure. Synonyme/abus de langage pour microplot, groupe de plante et consort.

**Comment by cpommier** [comment]
Moyenne genotypique : Entity: plant, char: emergenceDate

**Comment by cpommier** [comment]
In variable add : 
| Trait Entity |  Trait Entity Accession number |  Trait Characteristic |  Trait Characteristic Accession number |

**Comment by cpommier** [comment]
TODO: align this with EMPHASIS variable naming conventions

**Comment by erlefloch** [comment]
variable description is just optional free text field

**Comment by cpommier** [comment]
Entity (part of the plant, whole plant, group of plant e.g. canopy) on which the trait has been measured

**Comment by cpommier** [comment]
Characteristic measured. It includes physical measures (morphology, agronomy, phenology, intercepted light, etc...), molecular characteristics (chlorophyll, sugar concentration, etc...), stress and disease related characteristic, etc... This list is not exhaustive and can be freely adapted to adapt to innovative traits.
