### ISSUE TITLE
Biological material need explicit accession and lot number (needed for Mapping MIAPPE/BrAPI )

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#67]
Need to add explicitely:
BioligicalMaterialID --> seedLot/AccessionNumber
MaterialSource:instcode:accessionNumber

**Comment by cpommier** [comment]
@erlefloch see with Anne Françoise templates for the PEPR

**Comment by cpommier** [comment]
MIAPPE 1.1 fields : 

Biological material ID         Infraspecific name   Material source ID (Holding institute/stock centre, accession)
INRA:W95115_inra_2001   var. B73                      INRA:W95115_inra
lot                                                                MCPD  accession

**Comment by cpommier** [comment]
1.2 proposition : 

| Biological material ID    |     Infraspecific name |  Material source ID (Holding institute/stock centre, accession) | MaterialSource Instcode | MaterialSource Instname | MaterialSource ACCNUMB  | 
| --- | --- | ---| --- | ---|
| INRA:W95115_inra_2001  | var. B73         |             INRA:W95115_inra | | | |
| lot          |                                                      MCPD | accession | | | |

**Comment by erlefloch** [comment]
TODO: add examples from GNPIS

**Comment by erlefloch** [comment]
- Phenotyping example : phenotyping data outside EBI archives to be linked with genomic data conserved in EBI archives
(relevant for MIAPPE) -> proposition to add the Biosamples ID(s) as a synonym of the phenotyping observation unit ID. Examples could come from the AGENT project once published.  Or in a published GWAS paper.

- Multi-omic example: linking data in several EBI archives

**Comment by erlefloch** [comment]
proposition in https://github.com/MIAPPE/MIAPPE/commit/45317a6d72e013b424bd0941803da9a0a8899ef5. 
TODO @cpommier : review definitions, examples, formats and cardinality.
Also, should we update the original "Material source ID (Holding institute/stock centre, accession)" following its decomposition into different fields?

**Comment by erlefloch** [comment]
Done in https://github.com/MIAPPE/MIAPPE/commit/45317a6d72e013b424bd0941803da9a0a8899ef5 and https://github.com/MIAPPE/MIAPPE/commit/7fbf3c3116f357534818808a0ff4890ef5c5e1ab .

**Comment by pkersey** [comment]
The table is a bit confusing as one row is an example, and the other is a set of instructions.

**Comment by cpommier** [comment]
You are right, this is clarified in the updated data template available in the release.
