### ISSUE TITLE
Update the documentation to link CO_715 to the agroportal rather than cropontology where it is not available anymore

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#81]

**Comment by erlefloch** [comment]
currently we have :


line # | MIAPPE Check list | Definition | Example | Format | Cardinality
-- | -- | -- | -- | -- | --
DM-23 | Type of experimental design | Type of experimental  design of the study, in the form of an accession number from the Crop Ontology. | "CO_715:0000145” | Crop Ontology term (subclass of "CO_715:0000003") | 0-1
DM-27 | Type of growth facility | Type of growth facility in which the study was carried out, in the form of an accession number from the Crop Ontology. | “CO_715:0000162" | Crop Ontology term (subclass of "CO_715:0000005") | 0-1
DM-66 | Event accession number | Accession number of the event type in a suitable controlled vocabulary (Crop Ontology). | “CO_715:0000007” ; “CO_715:0000011” | Crop Ontology term (subclass of CO_715:0000006) | 0-1

**Comment by erlefloch** [comment]
create appendices files for "Type of experimental design" and  "Type of growth facility" ?
https://agroportal.lirmm.fr/ontologies/CO_715
and change format to "Crop Ontology term (subclass of "CO_715:xxx") or free text"

**Comment by erlefloch** [comment]
create appendices based on CO_715_0000003, CO_715_0000005, CO_715_0000006 
https://agroportal.lirmm.fr/ontologies/CO_715?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCO_715_0000003

**Comment by erlefloch** [comment]
there might be too little controlled vocabulary to make an appendix
