### ISSUE TITLE
add `Material Source Institute code`  and `Material Source Accession number`

### ISSUE THREAD

**Issue by erlefloch** [MIAPPE/MIAPPE#82]
Following EBI & DDBJ checklist discussions arising from bh23 in Japan, the following fields are needed:

| Material Source Institute code | FAO WIEWS code of the institute where the accession is maintained. The codes consist of the 3-letter ISO 3166 country code of the country where the institute is located plus a number (e.g. COL001). The current set of institute codes is available from http://www.fao.org/wiews. For those institutes not yet having an FAO Code, or for those with ‘obsolete’ codes, see ‘Common formatting rules (v)’. If no Institue code, create your own (Laboratory accronyme, Research Institute Acronyme, ...). |
| --- | --- |
| Material Source Accession number | This is the unique identifier for accessions within a genebank, and is assigned when a sample is entered into the genebank collection (e.g. ‘PI 113869’). If not a genebank, use a laboratory ID. In the case of a commercial Variety, use the variety anme or code. |
 
This is related to decomposition of the material source ID.

**Comment by erlefloch** [comment]
@cpommier : milestone is V2 or V1.2 ?

**Comment by pkersey** [comment]
'Acronym' with no 'e' in English.

**Comment by erlefloch** [comment]
> 'Acronym' with no 'e' in English.

the typo is absent from the data model, I had made a spelling correction at some point.
