### ISSUE TITLE
Add CV for cultivar / infraspecific name

### ISSUE THREAD

**Issue by erlefloch** [MIAPPE/MIAPPE#84]
as proposed today with CP, AFAB, VH

**Comment by cpommier** [comment]
Likewise, we could propose to have key value pair: `subsp:vinifera cv:pinot noir`

**Comment by erlefloch** [comment]
resolved with commit https://github.com/MIAPPE/MIAPPE/commit/d9632b718b1abede1dbd740d4948b30459878924 in branch 1.2

**Comment by cpommier** [comment]
Reopened during the MIAPPE SC, I don't remember if any action was needed. @PawelKrajewski could you comment or close please ?
