### ISSUE TITLE
rename MIAPPE-Checklist to MIAPPE

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#9]

**Comment by hcwi** [comment]
Done. Please note that now we have MIAPPE/MIAPPE path - both organisation and repo are the same.

**Comment by cpommier** [comment]
Great,

thanks Hanna
Cyril

Le 12 juil. 2018 à 10:30, hcwi <notifications@github.com<mailto:notifications@github.com>> a écrit :


Done. Please note that now we have MIAPPE/MIAPPE path - both organisation and repo are the same.
