### ISSUE TITLE
Issue DOIs for MIAPPE releases

### ISSUE THREAD

**Issue by erlefloch** [MIAPPE/MIAPPE#95]
It looks like there are DOIs for papers around MIAPPE but not for MIAPPE releases (data model, excel template...)
A possibility would be to use Zenodo: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content#issuing-a-persistent-identifier-for-your-repository-with-zenodo

**Comment by erlefloch** [comment]
Actually just like how it is made with rdmkit: https://doi.org/10.5281/zenodo.7085936

**Comment by erlefloch** [comment]
"You can add a CITATION file to your repository to help users correctly cite your software." https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by erlefloch** [comment]
question from @cpommier : is it passible to make DOIs for past versions ?

**Comment by cpommier** [comment]
Created ZENODO community : https://zenodo.org/communities/miappe

**Comment by cpommier** [comment]
And uploaded v1.0 and v1.1 versions of MIAPPE 
https://zenodo.org/communities/miappe

**Comment by raf64flo** [comment]
That's a great move, thanks! :+1:
