### ISSUE TITLE
Consider GPS location fuzziness for GDPR compliance

### ISSUE THREAD

**Issue by cpommier** [MIAPPE/MIAPPE#96]
See discussions with Célia M and possibly Fred dlM. 
Update the general recommendations, or those of all fields .
Possibilities: 
"Snce GPS location are possibly considered as personnal data, you should consider their "floutage" either by choosing the closest city or by removing the last two digits or any other mean."

**Comment by erlefloch** [comment]
to include in the Readme, and consider including the Readme in the pdf.

**Comment by erlefloch** [comment]
done in https://github.com/MIAPPE/MIAPPE/commit/f0e6a249b3e41746a611026e638784ecf30974ab
